In [24]:
#importing all the relevant libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
import seaborn as sns

from sklearn import model_selection as mdsel
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [25]:
#loading the data set
ins=pd.read_csv('train_dataset.csv')
ins.shape

(2500, 43)

In [26]:
#let's get a look at our dataset
ins.head()

,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,0.783193,0.030000,0.730769,17,34738,1,0,0,0,5,...,0,0,0,1,0,0,0,1,0,0
1,0.194244,0.020000,0.490385,15,4076,1,0,0,0,5,...,0,0,0,1,0,0,0,1,0,0
2,1.179761,0.063818,0.515734,20,8794,3,4,5,1,4,...,1,1,1,1,1,0,1,1,3,1
3,1.018113,0.011490,0.454373,15,4076,1,1,7,1,2,...,0,1,1,1,0,0,1,1,2,1
4,1.118493,0.070000,0.759615,17,34738,3,4,5,1,4,...,1,1,1,1,1,0,1,1,3,0

In [27]:
#let's begin data exploration
ins.describe()

,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.00000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000
mean,0.665712,0.065319,0.476587,13.191600,18142.978400,1.659200,1.812800,4.500800,0.934400,3.118400,...,0.494000,0.679200,0.679200,0.974800,0.53080,0.31920,0.679200,0.994000,1.623200,0.498000
std,0.380739,0.051642,0.114704,6.511824,16925.872081,1.030864,1.516138,3.024179,0.801969,2.300282,...,0.500064,0.466877,0.466877,0.156763,0.49915,0.46626,0.466877,0.077242,1.320424,0.500096
min,0.002750,0.000000,0.288462,0.000000,290.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,0.319288,0.020000,0.384927,8.000000,6112.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.00000,0.00000,0.000000,1.000000,0.000000,0.000000
50%,0.689989,0.056213,0.461538,15.000000,8794.000000,1.000000,2.000000,5.000000,1.000000,4.000000,...,0.000000,1.000000,1.000000,1.000000,1.00000,0.00000,1.000000,1.000000,2.000000,0.000000
75%,1.031323,0.100000,0.549239,20.000000,27003.000000,3.000000,3.000000,7.000000,2.000000,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,3.000000,1.000000
max,1.249958,0.380000,0.865385,21.000000,73430.000000,5.000000,5.000000,10.000000,2.000000,8.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,5.000000,1.000000

In [28]:
ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 43 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_tenure                     2500 non-null   float64
 1   age_of_car                        2500 non-null   float64
 2   age_of_policyholder               2500 non-null   float64
 3   area_cluster                      2500 non-null   int64
 4   population_density                2500 non-null   int64
 5   make                              2500 non-null   int64
 6   segment                           2500 non-null   int64
 7   model                             2500 non-null   int64
 8   fuel_type                         2500 non-null   int64
 9   max_torque                        2500 non-null   int64
 10  max_power                         2500 non-null   int64
 11  engine_type                       2500 non-null   int64
 12  airbags                           2500 non-null   int64
 13  is_esc                            2500 non-null   int64
 14  is_adjustable_steering            2500 non-null   int64
 15  is_tpms                           2500 non-null   int64
 16  is_parking_sensors                2500 non-null   int64
 17  is_parking_camera                 2500 non-null   int64
 18  rear_brakes_type                  2500 non-null   int64
 19  displacement                      2500 non-null   int64
 20  cylinder                          2500 non-null   int64
 21  transmission_type                 2500 non-null   int64
 22  gear_box                          2500 non-null   int64
 23  steering_type                     2500 non-null   int64
 24  turning_radius                    2500 non-null   float64
 25  length                            2500 non-null   int64
 26  width                             2500 non-null   int64
 27  height                            2500 non-null   int64
 28  gross_weight                      2500 non-null   int64
 29  is_front_fog_lights               2500 non-null   int64
 30  is_rear_window_wiper              2500 non-null   int64
 31  is_rear_window_washer             2500 non-null   int64
 32  is_rear_window_defogger           2500 non-null   int64
 33  is_brake_assist                   2500 non-null   int64
 34  is_power_door_locks               2500 non-null   int64
 35  is_central_locking                2500 non-null   int64
 36  is_power_steering                 2500 non-null   int64
 37  is_driver_seat_height_adjustable  2500 non-null   int64
 38  is_day_night_rear_view_mirror     2500 non-null   int64
 39  is_ecw                            2500 non-null   int64
 40  is_speed_alert                    2500 non-null   int64
 41  ncap_rating                       2500 non-null   int64
 42  is_claim                          2500 non-null   int64
dtypes: float64(4), int64(39)
memory usage: 840.0 KB

In [29]:
#now we know that we don't have any null values in any of the fields
#we should check variance of all the features so we can use only high variance features as low variance features don't affect target anyways
ins_features=ins.drop('is_claim',axis=1)
ins_var=VarianceThreshold(threshold=0.2)
ins_var.fit_transform(ins_features)
for feature in zip(ins_features.columns,ins_var.variances_):
    print(feature)

('policy_tenure', 0.1449039777905849)
('age_of_car', 0.0026658386751438534)
('age_of_policyholder', 0.013151730036492398)
('area_cluster', 42.38688944)
('population_density', 286370551.6347335)
('make', 1.06225536)
('segment', 2.29775616)
('model', 9.14199936)
('fuel_type', 0.6428966399999999)
('max_torque', 5.28918144)
('max_power', 5.80660416)
('engine_type', 6.106875359999999)
('airbags', 3.00793776)
('is_esc', 0.19220784)
('is_adjustable_steering', 0.24595503999999993)
('is_tpms', 0.16095744)
('is_parking_sensors', 0.04965424000000001)
('is_parking_camera', 0.21629104000000002)
('rear_brakes_type', 0.19449264000000002)
('displacement', 67235.81315504)
('cylinder', 0.24301104000000004)
('transmission_type', 0.24153599999999997)
('gear_box', 0.16379903999999998)
('steering_type', 0.9066065599999998)
('turning_radius', 0.04869256186201792)
('length', 92590.881996)
('width', 11885.979753440002)
('height', 5476.0718950400005)
('gross_weight', 41464.070156)
('is_front_fog_lights', 0.24938496000000004)
('is_rear_window_wiper', 0.18093616)
('is_rear_window_washer', 0.18093616)
('is_rear_window_defogger', 0.20539456)
('is_brake_assist', 0.24996399999999994)
('is_power_door_locks', 0.21788736000000003)
('is_central_locking', 0.21788736000000003)
('is_power_steering', 0.024564960000000004)
('is_driver_seat_height_adjustable', 0.24905135999999997)
('is_day_night_rear_view_mirror', 0.21731136000000006)
('is_ecw', 0.21788736000000003)
('is_speed_alert', 0.005964000000000001)
('ncap_rating', 1.74282176)

In [30]:
#hence, we use only those features which have variance greater than 0.2
not_features=['policy_tenure','age_of_car','age_of_policyholder','is_esc','is_tpms','is_parking_sensors','rear_brakes_type','gear_box','turning_radius','is_rear_window_wiper','is_rear_window_washer','is_power_steering','is_speed_alert']
ins_features=ins_features.drop(not_features,axis=1)
ins_features.shape

(2500, 29)

In [31]:
#taking the target variable as a separate column
ins_target=ins['is_claim']
ins_target.shape

(2500,)

In [58]:
#splitting given data into train and test sections
X_train,X_test,y_train,y_test=mdsel.train_test_split(ins_features,ins_target,test_size=0.35)
X_train.shape

(1625, 29)

In [59]:
X_train.head()

,area_cluster,population_density,make,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,...,gross_weight,is_front_fog_lights,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,ncap_rating
985,17,34738,1,2,7,2,0,6,8,2,...,1335,1,0,1,1,1,1,1,1,2
1963,11,27003,2,0,4,2,8,5,0,2,...,1155,0,0,0,1,1,0,1,1,2
1939,5,7788,1,3,3,2,0,6,2,2,...,1335,1,1,1,1,1,1,1,1,2
1076,13,3264,1,0,0,0,4,2,6,2,...,1203,0,0,0,0,0,0,0,0,0
36,5,7788,3,4,5,1,4,0,3,6,...,1720,1,1,1,1,1,1,0,1,3

In [60]:
#since all the features columns are more or less independent of each other, we can use a naive bayes classifier
#hence importing the model
from sklearn.naive_bayes import GaussianNB
nbc=GaussianNB()
nbc.fit(X_train,y_train)

GaussianNB()

In [61]:
#making predictions on the test dataset
y_pred=nbc.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [62]:
#checking the accuracy of our model
print(accuracy_score(y_pred,y_test)*100)

63.2

In [63]:
#now let's import the test data..for which our model will be evaluated
actual_test=pd.read_csv('test_dataset.csv')
actual_test.head()

,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,max_torque,...,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating
0,0.427864,0.000000,0.494703,17,34738,1,0,0,0,5,...,0,0,0,0,1,0,0,0,1,0
1,0.431038,0.000000,0.528846,16,21622,3,4,5,1,4,...,1,1,1,1,1,1,0,1,1,3
2,0.141176,0.040231,0.298077,4,5410,3,4,5,1,4,...,1,1,1,1,1,1,0,1,1,3
3,0.049489,0.000000,0.413462,10,27742,2,0,4,2,8,...,0,0,1,1,1,0,1,1,1,2
4,1.157184,0.060000,0.413462,17,34738,3,4,5,1,4,...,1,1,1,1,1,1,0,1,1,3

In [64]:
#dropping useless columns
actual_features=actual_test.drop(not_features,axis=1)
actual_features.head()

,area_cluster,population_density,make,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,...,gross_weight,is_front_fog_lights,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,ncap_rating
0,17,34738,1,0,0,0,5,2,6,2,...,1185,0,0,0,0,0,0,0,0,0
1,16,21622,3,4,5,1,4,0,3,6,...,1720,1,1,1,1,1,1,0,1,3
2,4,5410,3,4,5,1,4,0,3,6,...,1720,1,1,1,1,1,1,0,1,3
3,10,27742,2,0,4,2,8,5,0,2,...,1155,0,0,0,1,1,0,1,1,2
4,17,34738,3,4,5,1,4,0,3,6,...,1720,1,1,1,1,1,1,0,1,3

In [65]:
#making predictions
actual_predictions=nbc.predict(actual_features)
actual_predictions

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [70]:
#converting the array to an appropriate dataframe
predictions_df=pd.DataFrame(actual_predictions)
predictions_df.index=actual_test.index
predictions_df.columns=['is_claim']
predictions_df.head()

   is_claim
0         1
1         0
2         0
3         1
4         0

In [71]:
#saving the predictions dataframe as a csv file to be uploaded
predictions_df.to_csv("prediction_results.csv", index = False)